version: "3"

services:
  python-app:
    build: .
    container_name: python-app
    restart: always
    env_file:
      - .env
    volumes: 
      - ./:/app
    ports:
      - 8080:8080
    command: "python3 app.py"
    networks:
      - development

networks: 
  development:
      name: dev_network